global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using Chronos.Domain.Entities;
global using Chronos.Data.Context;
global using Chronos.Data.Repositories;
global using Chronos.Domain.Interfaces.Repository;
global using Chronos.Domain.Entities.Enums;
global using Bogus;
global using AutoFixture;
global using Moq;
